### ISSUE TITLE
possible issues with orgunit tables

### ISSUE THREAD

**Issue by jaliasd** [USAID-OHA-SI/Wavelength#10]
When I was joining the FY19_OrgUnits_Zimbabwe.csv to the munged HFR data, there were several sites that didn't join a UID. Upon investigation, I found that a few of the `orgunit` values had extra spaces between the text and the ` - ` causing them not to join. Not sure if this is an issue from the orghierarchy table DATIM or something that happens when the CSV is created via the API pull.

**Comment by achafetz** [comment]
Let's assume this was resolves 😄
