### ISSUE TITLE
Reporting type column

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/Wavelength#30]
New column to flag if data are reported by week or month, “period_type”
  - Option: “week”, “month”, “month agg”
  - Check at mech_code x indicator (x site?) level whether there are more than one date in the month being reported

**Comment by baboyma** [comment]
This will go under process_template()?

**Comment by achafetz** [comment]
@baboyma it would be its own function, but would run in [hfr_process_template()](https://github.com/USAID-OHA-SI/Wavelength/blob/master/R/hfr_process_template.R), probably before the validation?

**Comment by achafetz** [comment]
col name = "hfr_freq", checked by mech_code x indicator x orgunituid, `hfr_identify_freq()`

sits within `hfr_fix_date()` because it has to be run before `hfr_round_date()` at end of `hfr_fix_date()`
