### ISSUE TITLE
Restrict load_lookups() to import only one file

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/Wavelength#37]
Ran into an issue where I had two org hierarchy tables locally. `load_lookups()` appended both together on the read in since it used `vroom()`. We should update to only read in the latest file. Otherwise, when running the output checks, `is_orgunituid4ou()` then doubles the rows on the `left_join()`.

**Comment by baboyma** [comment]
I have updated the function to read the latest file in the folder.
This assumes that original files keep the dates at the end. Eg: ".*_orghierarchy_\\d{8}$"
