### ISSUE TITLE
coordinate error

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/Wavelength#47]
From Joe:

> When I call "pull_hierarchy" with all my relevant arguments I get an error (see below).  

![image](https://user-images.githubusercontent.com/8933069/218102918-ead17e89-ede7-4731-a7f9-214b7215317c.png)

Given other changes in DATIM this period, I wonder if something else changed?

FYI @baboyma

**Comment by achafetz** [comment]
issues appears to be coming from ln87

https://github.com/USAID-OHA-SI/Wavelength/blob/2b95ae3da1b7b34edcf17c1ec0cf4c535a4885a3/R/pull_hierarchy.R#L86-L88

Going to try removing that and adding it into line 88

**Comment by baboyma** [comment]
Taking a look now
